import { Recommendation } from "@forkfacts/models";

export const recommendations: Recommendation[] = [
  {
    category: "SUPERFOODS",
    collections: [
      { name: "Blueberries" },
      { name: "Kale" },
      { name: "Quinoa" },
      { name: "Chia seeds" },
      { name: "Spinach" },
      { name: "Greek yogurt" },
      { name: "Almonds" },
      { name: "Turmeric" },
      { name: "Green tea" },
      { name: "Avocado" },
      { name: "Sweet potatoes" },
      { name: "Garlic" },
      { name: "Cacao" },
      { name: "Mushrooms" },
    ],
  },
  {
    category: "MAGNESIUM RICH FOODS",
    collections: [
      { name: "Spinach" },
      { name: "Almonds" },
      { name: "Cashews" },
      { name: "Pumpkin seeds" },
      { name: "Black beans" },
      { name: "Avocado" },
      { name: "Dark chocolate" },
      { name: "Tofu" },
      { name: "Yogurt" },
      { name: "Bananas" },
      { name: "Dark leafy greens" },
      { name: "Lentils" },
    ],
  },
  {
    category: "FIBER RICH FOODS",
    collections: [
      { name: "Chia Seeds" },
      { name: "Flaxseeds" },
      { name: "Quinoa" },
      { name: "Whole Grain Bread" },
      { name: "Avocado" },
      { name: "Brussels Sprouts" },
      { name: "Artichokes" },
      { name: "Sweet Potatoes" },
      { name: "Spinach" },
      { name: "Kale" },
      { name: "Almonds" },
    ],
  },
  {
    category: "ZINC RICH FOODS",
    collections: [
      { name: "Pumpkin Seeds" },
      { name: "Hemp Seeds" },
      { name: "Cashews" },
      { name: "Quinoa" },
      { name: "Sesame Seeds" },
      { name: "Yogurt" },
      { name: "Spinach" },
      { name: "Dark Chocolate" },
    ],
  },
];
